Add support for the .NET 8 SDK (#93)
* Add support for the .NET 8 SDK

Downgrading Microsoft.CodeAnalysis.CSharp from version 4.13.0 to 4.11.0 enables using Zomp.SyncMethodGenerator with the .NET 8 SDK at the very small price of using `nameof(Nullable<int>.*)` instead of `nameof(Nullable<>.*)`

Currently, using Zomp.SyncMethodGenerator with the .NET 8 SDK fails with this error.
> error CS9057: The analyzer assembly 'Zomp.SyncMethodGenerator.dll' references version '4.13.0.0' of the compiler, which is newer than the currently running version '4.11.0.0'.

* Remove global.json file

* Restore the use of nameof with unbound generic in AsyncToSyncRewriter

* Update test packages to their latest versions